enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.5.3.cjs

packageExtensions:
  next@*:
    dependencies:
      "@vanilla-extract/next-plugin": "^2.4.7"
  "@toast-ui/editor@*":
    dependencies:
      prosemirror-transform: "*"
  "@toast-ui/react-editor@*":
    dependencies:
      prosemirror-transform: "*"
