export type IconType =
  | "search"
  | "theme"
  | "close"
  | "secret"
  | "secret_open"
  | "bell"
  | "light"
  | "dark"
  | "check"
  | "favorite_fill"
  | "favorite"
  | "left"
  | "right"
  | "up"
  | "down"
  | "comment"
  | "plus"
  | "minus"
  | "plus_circle"
  | "lock"
  | "lock_open"
  | "lock_color"
  | "enter_arrow";

export type IconSize = "xs" | "s" | "m" | "l" | "xl" | "h";
